### PR TITLE
Dc statehood option

### LINKED ISSUE #3: DC statehood option
File location:
states -> states.py -> States

Although we all wish DC became the 51st state, DC is not a state. However, in some instances DC is counted as a state.

Currently, DC is counted as a state in this package. However, a feature must be added to give the user the option to count DC as a state or not.

### PR DESCRIPTION
**Pull request by bjuspi**
Added DC statehood option to the class States_Abbreviated and States_Full_Name by adding a parameter into the constructor which defines whether or not to include DC as a state.

### CODE REVIEW

**Review by AColocho — APPROVED** [review]
Looks great! The only feedback I have is that it's common practice to place the __init__ function at the top of each class. No worries! I'm pushing code later to the repo, so I'll fix this. Thank you for the contribution!

**Comment by bjuspi** [comment]
No worries

**Comment by bjuspi** [comment]
We should probably add this constructor definition as well

**Comment by AColocho** [comment]
Do you mean the docstring? Regardless, feel free to create an issue to be reviewed and then to be added. I'm open to any suggestions that advance the project forward.

**Comment by bjuspi** [comment]
Sorry, just realized that you've updated the README regarding the DC Statehood option

**Pull request merged**
